### ISSUE TITLE
Provide a hint when browsing old version of documentation

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1080]
The same way as it happens on the Akka documentation pages, when somebody is browsing a version of the docs that is not the most current one, some kind of warning should be displayed informing the reader that there is a newer version available with a link to it.

**Comment by ktoso** [comment]
Absolutely, we need to "steal" this script: https://github.com/akka/akka/blob/master/akka-docs/_sphinx/themes/akka/static/warnOldDocs.js
Any takers?

**Comment by jlprat** [comment]
Speaking of which, isn't this script a little too aggressive with old versions? 

Go to http://doc.akka.io/docs/akka/2.4.18/ see message:  `This version of Akka (akka / 2.4.18) is outdated and not supported!` Thing is, 2.4.18 was released yesterday

**Comment by ktoso** [comment]
It's true though ;) People should move to 2.5.

I think it should not have the outdated flag though, that's the red warning.
This should be fixed in http://akka.io/versions.json the script is fine

**Comment by jlprat** [comment]
OK, this makes sense, I was only wondering about the "not supported" as it was released yesterday (clearly meaning being supported ;) )

**Comment by jlprat** [comment]
And regarding the issue, if it's just stealing that JS and including it in Akka HTTP docs template I could do it later today

**Comment by raboof** [comment]
That javascript popup is great, but doesn't solve the fact that google still seems to really like linking to old versions. Perhaps we should just generate each page with a `canonical` link pointing to `current` - created https://github.com/lightbend/paradox/issues/109 for that.

**Comment by jlprat** [comment]
Shall we close this one? Hint is there, and doing google searches now it seems to reply with the `current` URLs

**Comment by raboof** [comment]
Yes looks like it :+1:
