### ISSUE TITLE
FAILED ResponseRendererSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#332]
https://jenkins.akka.io:8498/job/akka-nightly/3694/consoleFull

This seems to have the same reason as before here https://github.com/akka/akka/issues/21088. So, we might want to change the timeout again.

**Comment by jonas** [comment]
Pasting here for searchability:

```
[info] - The 'Connection' header should be rendered correctly *** FAILED *** (3 seconds, 950 milliseconds)
[info]   TestFailedException was thrown during property evaluation. (ResponseRendererSpec.scala:573)
[info]     Message: (HTTP/1.0 200 OK
[info]   Server: akka-http/1.0.0
[info]   Date: Thu, 25 Aug 2011 09:10:29 GMT
[info]   Content-Type: text/plain; charset=UTF-8
[info]   
[info]   ENTITY,Some(false)) did not equal (HTTP/1.0 200 OK
[info]   Server: akka-http/1.0.0
[info]   Date: Thu, 25 Aug 2011 09:10:29 GMT
[info]   Content-Type: text/plain; charset=UTF-8
[info]   
[info]   ENTITY,Some(true))
[info]     Location: (ResponseRendererSpec.scala:574)
[info]     Occurred at table row 57 (zero based, not counting headings), which had values (
[info]       Req Prot = HttpProtocol(HTTP/1.0),
[info]       HEAD Req = false,
[info]       Req CH = None,
[info]       Res Prot = HttpProtocol(HTTP/1.0),
[info]       Res CH = Some(Connection: close),
[info]       Res CD = true,
[info]       Ren Conn = None,
[info]       Close = true
[info]     )
[info]   org.scalatest.exceptions.TableDrivenPropertyCheckFailedException:
[info]   at org.scalatest.enablers.TableAsserting$$anon$2.indicateFailure(TableAsserting.scala:2312)
[info]   at org.scalatest.enablers.TableAsserting$$anon$2.indicateFailure(TableAsserting.scala:2308)
[info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl$$anonfun$forAll$23.apply(TableAsserting.scala:832)
[info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl$$anonfun$forAll$23.apply(TableAsserting.scala:818)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
[info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl.forAll(TableAsserting.scala:818)
[info]   at org.scalatest.prop.TableFor8.apply(TableFor1.scala:1432)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$class.forAll(TableDrivenPropertyChecks.scala:479)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$.forAll(TableDrivenPropertyChecks.scala:1344)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anon$30.<init>(ResponseRendererSpec.scala:573)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
...
[info]   Cause: org.scalatest.exceptions.TestFailedException: (HTTP/1.0 200 OK
[info] Server: akka-http/1.0.0
[info] Date: Thu, 25 Aug 2011 09:10:29 GMT
[info] Content-Type: text/plain; charset=UTF-8
[info] 
[info] ENTITY,Some(false)) did not equal (HTTP/1.0 200 OK
[info] Server: akka-http/1.0.0
[info] Date: Thu, 25 Aug 2011 09:10:29 GMT
[info] Content-Type: text/plain; charset=UTF-8
[info] 
[info] ENTITY,Some(true))
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anon$30$$anonfun$5.apply(ResponseRendererSpec.scala:582)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anon$30$$anonfun$5.apply(ResponseRendererSpec.scala:573)
[info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl$$anonfun$forAll$23.apply(TableAsserting.scala:820)
[info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl$$anonfun$forAll$23.apply(TableAsserting.scala:818)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
[info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl.forAll(TableAsserting.scala:818)
[info]   at org.scalatest.prop.TableFor8.apply(TableFor1.scala:1432)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$class.forAll(TableDrivenPropertyChecks.scala:479)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$.forAll(TableDrivenPropertyChecks.scala:1344)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anon$30.<init>(ResponseRendererSpec.scala:573)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
...
```

**Comment by gosubpl** [comment]
This should be fixed now - timeout has been increased to `1000 ms`

**Comment by jonas** [comment]
@gosubpl The test failure in this ticket uses `renderTo` which has a default timeout of [3 seconds](https://github.com/akka/akka-http/blob/master/akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala#L599) so I think this is not fixed.

    [info] - The 'Connection' header should be rendered correctly *** FAILED *** (3 seconds, 950 milliseconds)
